### ISSUE TITLE
Set up GitHub pages for the digital garden 

### ISSUE THREAD

**Issue by DdimaPos** [prcave/digital_garden#4]
Use mkdocs material guide to setup the digital garden to be displayed correctly on website

**Comment by andyp1xe1** [comment]
I looked at your fork.
The mkdocs thing is nice since we can have search and all that, and also it's nice that we can use a github workflow to build.
But a couple things:
1. this repo is the actual markdown vault itself
2. the github pages website will be a separate repo with the name: prcave.github.io
3. the website will have a path to notes/

So we have to setup the website repo separately.

Also, would be nice if we can get rid of the "made with" footer the material-mkdocs adds in.

So my questions are:
- is it fast to build?
- can we add custom logo?
- can we remove the footer / modify it?
- how easy is it to make the notes a subsection of a larger website?
- is the pink and purple necessary :3

**Comment by DdimaPos** [comment]
1. After each commit in main it takes nearly 30 seconds to build
2. We can add custom logo, custom name near the logo, favicon and tab title
3. Don't now. I need to read [this](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/) article. It states that we can add a custom footer, header and much more
4. I need to see how you want this to look. Maybe it will be easy to integrate
5. Already fixed that. I am working now on theming

**Comment by andyp1xe1** [comment]
nice

**Comment by DdimaPos** [comment]
decided to use Quartz instead of mkdocs
